// <auto-generated />
namespace CadastroPessoas.Persistencia.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Criancao_Tabela_Pessoas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Criancao_Tabela_Pessoas));
        
        string IMigrationMetadata.Id
        {
            get { return "202004212107399_Criancao_Tabela_Pessoas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
